csax_nxsas_schema = {
    "h5_group_attributes": {

        "/entry:NX_class": "NXentry",
        "/entry/instrument:NX_class": "NXinstrument",
        "/entry/instrument/source:NX_class": "NXsource",
        "/entry/instrument/insertion_device:NX_class": "NXinsertion_device",

        "/entry/instrument/slit_0:NX_class": "NXslit",
        "/entry/instrument/slit_1:NX_class": "NXslit",

        "/entry/instrument/monochromator:NX_class": "NXmonochromator",
        "/entry/instrument/monochromator/crystal_1:NX_class": "NXcrystal",
        "/entry/instrument/monochromator/crystal_2:NX_class": "NXcrystal",

        "/entry/instrument/XBPM4:NX_class": "NXdetector_group",
        "/entry/instrument/XBPM4/XBPM4:NX_class": "NX_detector",
        "/entry/instrument/XBPM4/XBPM4_sum:NX_class": "NX_detector",
        "/entry/instrument/XBPM4/XBPM4_x:NX_class": "NX_detector",
        "/entry/instrument/XBPM4/XBPM4_y:NX_class": "NX_detector",
        "/entry/instrument/XBPM4/XBPM4_skew:NX_class": "NX_detector",

        "/entry/instrument/mirror:NX_class": "NXmirror",

        "/entry/instrument/XBPM5:NX_class": "NXdetector_group",
        "/entry/instrument/XBPM5/XBPM5:NX_class": "NX_detector",
        "/entry/instrument/XBPM5/XBPM5_sum:NX_class": "NX_detector",
        "/entry/instrument/XBPM5/XBPM5_x:NX_class": "NX_detector",
        "/entry/instrument/XBPM5/XBPM5_y:NX_class": "NX_detector",
        "/entry/instrument/XBPM5/XBPM5_skew:NX_class": "NX_detector",

        "/entry/instrument/slit_2:NX_class": "NXslit",

        "/entry/instrument/XBPM6:NX_class": "NXdetector_group",
        "/entry/instrument/XBPM6/XBPM6:NX_class": "NX_detector",
        "/entry/instrument/XBPM6/XBPM6_sum:NX_class": "NX_detector",
        "/entry/instrument/XBPM6/XBPM6_x:NX_class": "NX_detector",
        "/entry/instrument/XBPM6/XBPM6_y:NX_class": "NX_detector",
        "/entry/instrument/XBPM6/XBPM6_skew:NX_class": "NX_detector",

        "/entry/instrument/slit_3:NX_class": "NXslit",

        "/entry/instrument/filter_set:NX_class": "NXattenuator",

        "/entry/instrument/slit_4:NX_class": "NXslit",

        "/entry/instrument/beam_stop_1:NX_class": "NX_beamstop",
        "/entry/instrument/beam_stop_2:NX_class": "NX_beamstop",

        "/entry/plottable_data:NX_class": "NXdata",

        "/entry/sample:NX_class": "NXsample",
        "/entry/control:NX_class": "NXmonitor"
    },

    "h5_dataset_attributes": {

        # Dataset classes.

        "/entry/title:NX_class": "NX_CHAR",
        "/entry/start_time:NX_class": "NX_DATE_TIME",
        "/entry/end_time:NX_class": "NX_DATE_TIME",
        "/entry/definition:NX_class": "NX_CHAR",
        "/entry/instrument/name:NX_class": "NX_CHAR",
        "/entry/instrument/source/type:NX_class": "NX_CHAR",
        "/entry/instrument/source/name:NX_class": "NX_CHAR",
        "/entry/instrument/source/probe:NX_class": "NX_CHAR",
        "/entry/instrument/source/distance:NX_class": "NX_FLOAT",
        "/entry/instrument/source/sigma_x:NX_class": "NX_FLOAT",
        "/entry/instrument/source/sigma_y:NX_class": "NX_FLOAT",
        "/entry/instrument/source/divergence_x:NX_class": "NX_FLOAT",
        "/entry/instrument/source/divergence_y:NX_class": "NX_FLOAT",
        "/entry/instrument/source/current:NX_class": "NX_FLOAT",
        "/entry/instrument/insertion_device/type:NX_class": "NX_CHAR",
        "/entry/instrument/insertion_device/gap:NX_class": "NX_FLOAT",
        "/entry/instrument/insertion_device/k:NX_class": "NX_FLOAT",
        "/entry/instrument/insertion_device/length:NX_class": "NX_FLOAT",
        "/entry/instrument/insertion_device/harmonic:NX_class": "NX_INT",
        "/entry/instrument/slit_0/material:NX_class": "NX_CHAR",
        "/entry/instrument/slit_0/description:NX_class": "NX_CHAR",
        "/entry/instrument/slit_0/x_gap:NX_class": "NX_FLOAT",
        "/entry/instrument/slit_0/distance:NX_class": "NX_FLOAT",
        "/entry/instrument/slit_0/x_translation:NX_class": "NX_FLOAT",
        "/entry/instrument/slit_1/material:NX_class": "NX_CHAR",
        "/entry/instrument/slit_1/description:NX_class": "NX_CHAR",
        "/entry/instrument/slit_1/x_gap:NX_class": "NX_FLOAT",
        "/entry/instrument/slit_1/y_gap:NX_class": "NX_FLOAT",
        "/entry/instrument/slit_1/distance:NX_class": "NX_FLOAT",
        "/entry/instrument/slit_1/x_translation:NX_class": "NX_FLOAT",
        "/entry/instrument/slit_1/height:NX_class": "NX_FLOAT",
        "/entry/instrument/monochromator/wavelength:NX_class": "NX_FLOAT",
        "/entry/instrument/monochromator/wavelength_spread:NX_class": "NX_FLOAT",
        "/entry/instrument/monochromator/energy:NX_class": "NX_FLOAT",
        "/entry/instrument/monochromator/type:NX_class": "NXnote",
        "/entry/instrument/monochromator/distance:NX_class": "NX_FLOAT",
        "/entry/instrument/monochromator/crystal_1/usage:NX_class": "NX_CHAR",
        "/entry/instrument/monochromator/crystal_1/type:NX_class": "NX_CHAR",
        "/entry/instrument/monochromator/crystal_1/order_no:NX_class": "NX_INT",
        "/entry/instrument/monochromator/crystal_1/reflection:NX_class": "NX_INT",
        "/entry/instrument/monochromator/crystal_1/bragg_angle:NX_class": "NX_FLOAT",
        "/entry/instrument/monochromator/crystal_1/temperature:NX_class": "NX_FLOAT",
        "/entry/instrument/monochromator/crystal_2/usage:NX_class": "NX_CHAR",
        "/entry/instrument/monochromator/crystal_2/type:NX_class": "NX_CHAR",
        "/entry/instrument/monochromator/crystal_2/order_no:NX_class": "NX_INT",
        "/entry/instrument/monochromator/crystal_2/reflection:NX_class": "NX_INT",
        "/entry/instrument/monochromator/crystal_2/bragg_angle:NX_class": "NX_FLOAT",
        "/entry/instrument/monochromator/crystal_2/temperature:NX_class": "NX_FLOAT",
        "/entry/instrument/monochromator/crystal_2/bend_x:NX_class": "NX_FLOAT",
        "/entry/instrument/XBPM4/group_names:NX_class": "NX_CHAR",
        "/entry/instrument/XBPM4/group_index:NX_class": "NX_INT",
        "/entry/instrument/XBPM4/group_parent:NX_class": "NX_INT",
        "/entry/instrument/XBPM4/XBPM4/distance:NX_class": "NX_FLOAT",
        "/entry/instrument/XBPM4/XBPM4/description:NX_class": "NX_CHAR",
        "/entry/instrument/XBPM4/XBPM4/type:NX_class": "NX_CHAR",
        "/entry/instrument/XBPM4/XBPM4/calibration_date:NX_class": "NX_CHAR",
        "/entry/instrument/XBPM4/XBPM4/count_time:NX_class": "NX_NUMBER",
        "/entry/instrument/XBPM4/XBPM4/gain_setting:NX_class": "NX_FLOAT",
        "/entry/instrument/XBPM4/XBPM4_sum/data:NX_class": "NX_FLOAT",
        "/entry/instrument/XBPM4/XBPM4_sum/description:NX_class": "NX_CHAR",
        "/entry/instrument/XBPM4/XBPM4_sum/saturation_value:NX_class": "NX_FLOAT",
        "/entry/instrument/XBPM4/XBPM4_x/data:NX_class": "NX_FLOAT",
        "/entry/instrument/XBPM4/XBPM4_x/description:NX_class": "NX_CHAR",
        "/entry/instrument/XBPM4/XBPM4_y/data:NX_class": "NX_FLOAT",
        "/entry/instrument/XBPM4/XBPM4_y/description:NX_class": "NX_CHAR",
        "/entry/instrument/XBPM4/XBPM4_skew/data:NX_class": "NX_FLOAT",
        "/entry/instrument/XBPM4/XBPM4_skew/description:NX_class": "NX_CHAR",
        "/entry/instrument/mirror/type:NX_class": "NX_CHAR",
        "/entry/instrument/mirror/description:NX_class": "NX_CHAR",
        "/entry/instrument/mirror/incident_angle:NX_class": "NX_FLOAT",
        "/entry/instrument/mirror/substrate_material:NX_class": "NX_CHAR",
        "/entry/instrument/mirror/coating_material:NX_class": "NX_CHAR",
        "/entry/instrument/mirror/bend_y:NX_class": "NX_FLOAT",
        "/entry/instrument/mirror/distance:NX_class": "NX_FLOAT",
        "/entry/instrument/XBPM5/group_names:NX_class": "NX_CHAR",
        "/entry/instrument/XBPM5/group_index:NX_class": "NX_INT",
        "/entry/instrument/XBPM5/group_parent:NX_class": "NX_INT",
        "/entry/instrument/XBPM5/XBPM5/distance:NX_class": "NX_FLOAT",
        "/entry/instrument/XBPM5/XBPM5/description:NX_class": "NX_CHAR",
        "/entry/instrument/XBPM5/XBPM5/type:NX_class": "NX_CHAR",
        "/entry/instrument/XBPM5/XBPM5/calibration_date:NX_class": "NX_CHAR",
        "/entry/instrument/XBPM5/XBPM5/count_time:NX_class": "NX_NUMBER",
        "/entry/instrument/XBPM5/XBPM5/gain_setting:NX_class": "NX_FLOAT",
        "/entry/instrument/XBPM5/XBPM5_sum/data:NX_class": "NX_FLOAT",
        "/entry/instrument/XBPM5/XBPM5_sum/description:NX_class": "NX_CHAR",
        "/entry/instrument/XBPM5/XBPM5_sum/saturation_value:NX_class": "NX_FLOAT",
        "/entry/instrument/XBPM5/XBPM5_x/data:NX_class": "NX_FLOAT",
        "/entry/instrument/XBPM5/XBPM5_x/description:NX_class": "NX_CHAR",
        "/entry/instrument/XBPM5/XBPM5_y/data:NX_class": "NX_FLOAT",
        "/entry/instrument/XBPM5/XBPM5_y/description:NX_class": "NX_CHAR",
        "/entry/instrument/XBPM5/XBPM5_skew/data:NX_class": "NX_FLOAT",
        "/entry/instrument/XBPM5/XBPM5_skew/description:NX_class": "NX_CHAR",
        "/entry/instrument/slit_2/material:NX_class": "NX_CHAR",
        "/entry/instrument/slit_2/description:NX_class": "NX_CHAR",
        "/entry/instrument/slit_2/x_gap:NX_class": "NX_FLOAT",
        "/entry/instrument/slit_2/y_gap:NX_class": "NX_FLOAT",
        "/entry/instrument/slit_2/distance:NX_class": "NX_FLOAT",
        "/entry/instrument/slit_2/x_translation:NX_class": "NX_FLOAT",
        "/entry/instrument/slit_2/height:NX_class": "NX_FLOAT",
        "/entry/instrument/XBPM6/group_names:NX_class": "NX_CHAR",
        "/entry/instrument/XBPM6/group_index:NX_class": "NX_INT",
        "/entry/instrument/XBPM6/group_parent:NX_class": "NX_INT",
        "/entry/instrument/XBPM6/XBPM6/distance:NX_class": "NX_FLOAT",
        "/entry/instrument/XBPM6/XBPM6/description:NX_class": "NX_CHAR",
        "/entry/instrument/XBPM6/XBPM6/type:NX_class": "NX_CHAR",
        "/entry/instrument/XBPM6/XBPM6/calibration_date:NX_class": "NX_CHAR",
        "/entry/instrument/XBPM6/XBPM6/count_time:NX_class": "NX_NUMBER",
        "/entry/instrument/XBPM6/XBPM6/gain_setting:NX_class": "NX_FLOAT",
        "/entry/instrument/XBPM6/XBPM6_sum/data:NX_class": "NX_FLOAT",
        "/entry/instrument/XBPM6/XBPM6_sum/description:NX_class": "NX_CHAR",
        "/entry/instrument/XBPM6/XBPM6_sum/saturation_value:NX_class": "NX_FLOAT",
        "/entry/instrument/XBPM6/XBPM6_x/data:NX_class": "NX_FLOAT",
        "/entry/instrument/XBPM6/XBPM6_x/description:NX_class": "NX_CHAR",
        "/entry/instrument/XBPM6/XBPM6_y/data:NX_class": "NX_FLOAT",
        "/entry/instrument/XBPM6/XBPM6_y/description:NX_class": "NX_CHAR",
        "/entry/instrument/XBPM6/XBPM6_skew/data:NX_class": "NX_FLOAT",
        "/entry/instrument/XBPM6/XBPM6_skew/description:NX_class": "NX_CHAR",
        "/entry/instrument/slit_3/material:NX_class": "NX_CHAR",
        "/entry/instrument/slit_3/description:NX_class": "NX_CHAR",
        "/entry/instrument/slit_3/x_gap:NX_class": "NX_FLOAT",
        "/entry/instrument/slit_3/y_gap:NX_class": "NX_FLOAT",
        "/entry/instrument/slit_3/distance:NX_class": "NX_FLOAT",
        "/entry/instrument/slit_3/x_translation:NX_class": "NX_FLOAT",
        "/entry/instrument/slit_3/height:NX_class": "NX_FLOAT",
        "/entry/instrument/filter_set/distance:NX_class": "NX_FLOAT",
        "/entry/instrument/filter_set/description:NX_class": "NX_CHAR",
        "/entry/instrument/filter_set/type:NX_class": "NX_CHAR",
        "/entry/instrument/filter_set/attenuator_transmission:NX_class": "NX_FLOAT",
        "/entry/instrument/slit_4/material:NX_class": "NX_CHAR",
        "/entry/instrument/slit_4/description:NX_class": "NX_CHAR",
        "/entry/instrument/slit_4/x_gap:NX_class": "NX_FLOAT",
        "/entry/instrument/slit_4/y_gap:NX_class": "NX_FLOAT",
        "/entry/instrument/slit_4/distance:NX_class": "NX_FLOAT",
        "/entry/instrument/slit_4/x_translation:NX_class": "NX_FLOAT",
        "/entry/instrument/slit_4/height:NX_class": "NX_FLOAT",

        "/entry/instrument/beam_stop_1/description:NX_class": "NX_CHAR",
        "/entry/instrument/beam_stop_1/size:NX_class": "NX_FLOAT",
        "/entry/instrument/beam_stop_1/x:NX_class": "NX_FLOAT",
        "/entry/instrument/beam_stop_1/y:NX_class": "NX_FLOAT",
        "/entry/instrument/beam_stop_1/distance_to_detector:NX_class": "NX_FLOAT",
        "/entry/instrument/beam_stop_1/status:NX_class": "NX_CHAR",

        "/entry/instrument/beam_stop_2/description:NX_class": "NX_CHAR",
        "/entry/instrument/beam_stop_2/size_x:NX_class": "NX_FLOAT",
        "/entry/instrument/beam_stop_2/size_y:NX_class": "NX_FLOAT",
        "/entry/instrument/beam_stop_2/x:NX_class": "NX_FLOAT",
        "/entry/instrument/beam_stop_2/y:NX_class": "NX_FLOAT",
        "/entry/instrument/beam_stop_2/distance_to_detector:NX_class": "NX_FLOAT",
        "/entry/instrument/beam_stop_2/status:NX_class": "NX_CHAR",
        "/entry/instrument/beam_stop_2/data:NX_class": "NX_CHAR",

        "/entry/sample/name:NX_class": "NX_CHAR",
        "/entry/sample/aequatorial_angle:NX_class": "NX_FLOAT",
        "/entry/sample/description:NX_class": "NX_CHAR",
        "/entry/sample/x_translation:NX_class": "NX_FLOAT",
        "/entry/sample/y_translation:NX_class": "NX_FLOAT",
        "/entry/sample/temperature_log:NX_class": "NX_FLOAT",

        "/entry/control/mode:NX_class": "NX_CHAR",
        "/entry/control/integral:NX_class": "NX_FLOAT",
        "/entry/control/note:NX_class": "NXnote",

        # Dataset units.

        "/entry/instrument/source/sigma_x:NX_LENGTH": "mm",
        "/entry/instrument/source/sigma_y:NX_LENGTH": "mm",
        "/entry/instrument/source/divergence_x:NX_ANGLE": "radians",
        "/entry/instrument/source/divergence_y:NX_ANGLE": "radians",
        "/entry/instrument/source/current:NX_CURRENT": "mA",

        "/entry/instrument/insertion_device/gap:NX_LENGTH": "mm",
        "/entry/instrument/insertion_device/k:NX_DIMENSIONLESS": True,
        "/entry/instrument/insertion_device/length:NX_LENGTH": "mm",
        "/entry/instrument/insertion_device/harmonic:NX_UNITLESS": "true",

        "/entry/instrument/slit_0/x_gap:NX_LENGTH": "mm",
        "/entry/instrument/slit_0/distance:NX_LENGTH": "mm",
        "/entry/instrument/slit_0/x_translation:NX_LENGTH": "mm",

        "/entry/instrument/slit_1/x_gap:NX_LENGTH": "mm",
        "/entry/instrument/slit_1/y_gap:NX_LENGTH": "mm",
        "/entry/instrument/slit_1/distance:NX_LENGTH": "mm",
        "/entry/instrument/slit_1/x_translation:NX_LENGTH": "mm",
        "/entry/instrument/slit_1/height:NX_LENGTH": "mm",

        "/entry/instrument/monochromator/wavelength:NX_WAVELENGTH": "Angstrom",
        "/entry/instrument/monochromator/energy:NX_ENERGY": "keV",
        "/entry/instrument/monochromator/distance:NX_LENGTH": "mm",

        "/entry/instrument/monochromator/crystal_1/reflection:NX_UNITLESS": "",
        "/entry/instrument/monochromator/crystal_1/bragg_angle:NX_ANGLE": "degrees",

        "/entry/instrument/monochromator/crystal_2/reflection:NX_UNITLESS": "",
        "/entry/instrument/monochromator/crystal_2/bragg_angle:NX_ANGLE": "degrees",
        "/entry/instrument/monochromator/crystal_2/bend_x:NX_ANY": "",

        "/entry/instrument/XBPM4/XBPM4/count_time:NX_TIME": "s",

        "/entry/instrument/mirror/incident_angle:NX_ANGLE": "degrees",
        "/entry/instrument/mirror/bend_y:NX_ANY": "",
        "/entry/instrument/mirror/distance:NX_LENGTH": "mm",

        "/entry/instrument/XBPM5/XBPM5/count_time:NX_TIME": "s",

        "/entry/instrument/slit_2/x_gap:NX_LENGTH": "mm",
        "/entry/instrument/slit_2/y_gap:NX_LENGTH": "mm",
        "/entry/instrument/slit_2/distance:NX_LENGTH": "mm",
        "/entry/instrument/slit_2/x_translation:NX_LENGTH": "mm",
        "/entry/instrument/slit_2/height:NX_LENGTH": "mm",

        "/entry/instrument/XBPM6/XBPM6/count_time:NX_TIME": "s",

        "/entry/instrument/slit_3/x_gap:NX_LENGTH": "mm",
        "/entry/instrument/slit_3/y_gap:NX_LENGTH": "mm",
        "/entry/instrument/slit_3/distance:NX_LENGTH": "mm",
        "/entry/instrument/slit_3/x_translation:NX_LENGTH": "mm",
        "/entry/instrument/slit_3/height:NX_LENGTH": "mm",

        "/entry/instrument/filter_set/distance:NX_LENGTH": "mm",

        "/entry/instrument/slit_4/x_gap:NX_LENGTH": "mm",
        "/entry/instrument/slit_4/y_gap:NX_LENGTH": "mm",
        "/entry/instrument/slit_4/distance:NX_LENGTH": "mm",
        "/entry/instrument/slit_4/x_translation:NX_LENGTH": "mm",
        "/entry/instrument/slit_4/height:NX_LENGTH": "mm",

        "/entry/instrument/beam_stop_1/size:NX_LENGTH": "mm",
        "/entry/instrument/beam_stop_1/x:NX_LENGTH": "mm",
        "/entry/instrument/beam_stop_1/y:NX_LENGTH": "mm",
        "/entry/instrument/beam_stop_1/distance_to_detector:NX_LENGTH": "mm",

        "/entry/instrument/beam_stop_2/size_x:NX_LENGTH": "mm",
        "/entry/instrument/beam_stop_2/size_y:NX_LENGTH": "mm",
        "/entry/instrument/beam_stop_2/x:NX_LENGTH": "mm",
        "/entry/instrument/beam_stop_2/y:NX_LENGTH": "mm",
        "/entry/instrument/beam_stop_2/distance_to_detector:NX_LENGTH": "mm",

        "/entry/sample/aequatorial_angle:NX_ANGLE": "deg",
        "/entry/sample/x_translation:NX_LENGTH": "mm",
        "/entry/sample/y_translation:NX_LENGTH": "mm"
    }
}

csax_nxsas_values = {
    "h5_dataset_fixed_values": {
        "/entry/end_time": "???",
        "/entry/definition": "NXsas",

        "/entry/instrument/name": "cSAXS beamline",

        "/entry/instrument/source/type": "Synchrotron X-ray Source",
        "/entry/instrument/source/name": "Swiss Light Source",
        "/entry/instrument/source/probe": "x-ray",
        "/entry/instrument/source/sigma_x": 0.202,
        "/entry/instrument/source/sigma_y": 0.018,
        "/entry/instrument/source/divergence_x": 0.000135,
        "/entry/instrument/source/divergence_y": 0.000025,

        "/entry/instrument/insertion_device/type": "undulator",
        "/entry/instrument/insertion_device/k": 2.46,
        "/entry/instrument/insertion_device/length": 1820.0,

        "/entry/instrument/slit_0/material": "OFHC Cu",
        "/entry/instrument/slit_0/description": "Horizontal secondary source slit",

        "/entry/instrument/slit_1/material": "OFHC Cu",
        "/entry/instrument/slit_1/description": "Slit 1, optics hutch",

        "/entry/instrument/monochromator/wavelength_spread": 0.0001,
        "/entry/instrument/monochromator/type": "Double crystal fixed exit monochromator",

        "/entry/instrument/monochromator/crystal_1/usage": "Bragg",
        "/entry/instrument/monochromator/crystal_1/type": "Si",
        "/entry/instrument/monochromator/crystal_1/order_no": 1,
        "/entry/instrument/monochromator/crystal_1/reflection": [1, 1, 1],

        "/entry/instrument/monochromator/crystal_2/usage": "Bragg",
        "/entry/instrument/monochromator/crystal_2/type": "Si",
        "/entry/instrument/monochromator/crystal_2/order_no": 2,
        "/entry/instrument/monochromator/crystal_2/reflection": [1, 1, 1],

        "/entry/instrument/XBPM4/group_names": "XBPM4, XBPM4_sum, XBPM4_x, XBPM4_y, XBPM4_skew",
        "/entry/instrument/XBPM4/group_index": 2,
        "/entry/instrument/XBPM4/group_parent": [-1, 1, 1, 1, 1],

        "/entry/instrument/XBPM4/XBPM4/distance": float('nan'),
        "/entry/instrument/XBPM4/XBPM4/description": "Four quadrant x-ray beam position monitor",
        "/entry/instrument/XBPM4/XBPM4/type": "???",
        "/entry/instrument/XBPM4/XBPM4/calibration_date": "???",

        "/entry/instrument/XBPM4/XBPM4_sum/description": "Sum of counts for the four quadrants",
        "/entry/instrument/XBPM4/XBPM4_x/description": "Normalized difference of counts between left "
                                                       "and right quadrants",
        "/entry/instrument/XBPM4/XBPM4_y/description": "Normalized difference of counts between high and low quadrants",
        "/entry/instrument/XBPM4/XBPM4_skew/description": "Normalized difference of counts between diagonal quadrants",

        "/entry/instrument/mirror/type": "single",
        "/entry/instrument/mirror/description": "Grazing incidence mirror to reject high-harmonic wavelengths from the "
                                                "monochromator. There are three coating options available that are "
                                                "used depending on the X-ray energy, no coating (SiO2), rhodium (Rh) "
                                                "or platinum (Pt).",
        "/entry/instrument/mirror/substrate_material": "SiO2",

        "/entry/instrument/XBPM5/group_names": "XBPM5, XBPM5_sum, XBPM5_x, XBPM5_y, XBPM5_skew",
        "/entry/instrument/XBPM5/group_index": 3,
        "/entry/instrument/XBPM5/group_parent": [-1, 1, 1, 1, 1],

        "/entry/instrument/XBPM5/XBPM5/distance": float('nan'),
        "/entry/instrument/XBPM5/XBPM5/description": "Four quadrant x-ray beam position monitor",
        "/entry/instrument/XBPM5/XBPM5/type": "???",
        "/entry/instrument/XBPM5/XBPM5/calibration_date": "???",

        "/entry/instrument/XBPM5/XBPM5_sum/description": "Sum of counts for the four quadrants",
        "/entry/instrument/XBPM5/XBPM5_x/description": "Normalized difference of counts between left and "
                                                       "right quadrants",
        "/entry/instrument/XBPM5/XBPM5_y/description": "Normalized difference of counts between high and low quadrants",
        "/entry/instrument/XBPM5/XBPM5_skew/description": "Normalized difference of counts between diagonal quadrants",

        "/entry/instrument/slit_2/material": "Ag",
        "/entry/instrument/slit_2/description": "Slit 2, optics hutch",

        "/entry/instrument/XBPM6/group_names": "XBPM6, XBPM6_sum, XBPM6_x, XBPM6_y, XBPM6_skew",
        "/entry/instrument/XBPM6/group_index": 4,
        "/entry/instrument/XBPM6/group_parent": [-1, 1, 1, 1, 1],

        "/entry/instrument/XBPM6/XBPM6/distance": float('nan'),
        "/entry/instrument/XBPM6/XBPM6/description": "Four quadrant x-ray beam position monitor",
        "/entry/instrument/XBPM6/XBPM6/type": "???",
        "/entry/instrument/XBPM6/XBPM6/calibration_date": "???",

        "/entry/instrument/XBPM6/XBPM6_sum/description": "Sum of counts for the four quadrants",
        "/entry/instrument/XBPM6/XBPM6_x/description": "Normalized difference of counts between left and "
                                                       "right quadrants",
        "/entry/instrument/XBPM6/XBPM6_y/description": "Normalized difference of counts between high and low quadrants",
        "/entry/instrument/XBPM6/XBPM6_skew/description": "Normalized difference of counts between diagonal quadrants",

        "/entry/instrument/slit_3/material": "Si",
        "/entry/instrument/slit_3/description": "Slit 3, experimental hutch, exposure box",

        "/entry/instrument/filter_set/description": "The filter set consists of 4 linear stages, each with five "
                                                    "filter positions. Additionally each one allows for an out "
                                                    "position to allow no filtering.",

        "/entry/instrument/slit_4/material": "Si",
        "/entry/instrument/slit_4/description": "Slit 4, experimental hutch, exposure box",

        "/entry/instrument/beam_stop_1/description": "circular",
        "/entry/instrument/beam_stop_1/size": 3.0,

        "/entry/instrument/beam_stop_2/description": "rectangular",
        "/entry/instrument/beam_stop_2/size_x": 5.00,
        "/entry/instrument/beam_stop_2/size_y": 2.25,

        "/entry/sample/aequatorial_angle": 1.0,

        "/entry/control/note": "monitor",
        "/entry/control/mode": "Value from bpm4s"
    },

    "h5_dataset_direct_input_values": {
        "date": "/entry/start_time",
        "scan": "/entry/title",
        "curr": "/entry/instrument/source/current",
        "idgap": "/entry/instrument/insertion_device/gap",
        "harmonic": "/entry/instrument/insertion_device/harmonic",
        "sl0wh": "/entry/instrument/slit_0/x_gap",
        "sl0ch": "/entry/instrument/slit_0/x_translation",
        "sl1wh": "/entry/instrument/slit_1/x_gap",
        "sl1wv": "/entry/instrument/slit_1/y_gap",
        "sl1ch": "/entry/instrument/slit_1/x_translation",
        "sl1cv": "/entry/instrument/slit_1/height",
        "mokev": "/entry/instrument/monochromator/energy",
        "moth1": ["/entry/instrument/monochromator/crystal_1/bragg_angle",
                  "/entry/instrument/monochromator/crystal_2/bragg_angle"],
        "temp_mono_cryst_1": "/entry/instrument/monochromator/crystal_1/temperature",
        "temp_mono_cryst_2": "/entry/instrument/monochromator/crystal_2/temperature",
        "mobd": "/entry/instrument/monochromator/crystal_2/bend_x",
        "sec": ["/entry/instrument/XBPM4/XBPM4/count_time",
                "/entry/instrument/XBPM5/XBPM5/count_time",
                "/entry/instrument/XBPM6/XBPM6/count_time"],
        "bpm4_gain_setting": "/entry/instrument/XBPM4/XBPM4/gain_setting",
        "bpm4s": ["/entry/instrument/XBPM4/XBPM4_sum/data",
                  "/entry/control/integral"],
        "bpm4_saturation_value": "/entry/instrument/XBPM4/XBPM4_sum/saturation_value",
        "bpm4x": "/entry/instrument/XBPM4/XBPM4_x/data",
        "bpm4y": "/entry/instrument/XBPM4/XBPM4_y/data",
        "bpm4z": "/entry/instrument/XBPM4/XBPM4_skew/data",
        "mith": "/entry/instrument/mirror/incident_angle",
        "mirror_coating": "/entry/instrument/mirror/coating_material",
        "mibd": "/entry/instrument/mirror/bend_y",
        "bpm5_gain_setting": "/entry/instrument/XBPM5/XBPM5/gain_setting",
        "bpm5s": "/entry/instrument/XBPM5/XBPM5_sum/data",
        "bpm5_saturation_value": "/entry/instrument/XBPM5/XBPM5_sum/saturation_value",
        "bpm5x": "/entry/instrument/XBPM5/XBPM5_x/data",
        "bpm5y": "/entry/instrument/XBPM5/XBPM5_y/data",
        "bpm5z": "/entry/instrument/XBPM5/XBPM5_skew/data",
        "sl2wh": "/entry/instrument/slit_2/x_gap",
        "sl2wv": "/entry/instrument/slit_2/y_gap",
        "sl2ch": "/entry/instrument/slit_2/x_translation",
        "sl2cv": "/entry/instrument/slit_2/height",
        "bpm6_gain_setting": "/entry/instrument/XBPM6/XBPM6/gain_setting",
        "bpm6s": "/entry/instrument/XBPM6/XBPM6_sum/data",
        "bpm6_saturation_value": "/entry/instrument/XBPM6/XBPM6_sum/saturation_value",
        "bpm6x": "/entry/instrument/XBPM6/XBPM6_x/data",
        "bpm6y": "/entry/instrument/XBPM6/XBPM6_y/data",
        "bpm6z": "/entry/instrument/XBPM6/XBPM6_skew/data",
        "sl3wh": "/entry/instrument/slit_3/x_gap",
        "sl3wv": "/entry/instrument/slit_3/y_gap",
        "sl3ch": "/entry/instrument/slit_3/x_translation",
        "sl3cv": "/entry/instrument/slit_3/height",
        "fil_comb_description": "/entry/instrument/filter_set/type",
        "sl4wh": "/entry/instrument/slit_4/x_gap",
        "sl4wv": "/entry/instrument/slit_4/y_gap",
        "sl4ch": "/entry/instrument/slit_4/x_translation",
        "sl4cv": "/entry/instrument/slit_4/height",
        "bs1x": "/entry/instrument/beam_stop_1/x",
        "bs1y": "/entry/instrument/beam_stop_1/y",
        "bs1_det_dist": "/entry/instrument/beam_stop_1/distance_to_detector",
        "bs1_status": "/entry/instrument/beam_stop_1/status",
        "bs2x": "/entry/instrument/beam_stop_2/x",
        "bs2y": "/entry/instrument/beam_stop_2/y",
        "bs2_det_dist": "/entry/instrument/beam_stop_2/distance_to_detector",
        "bs2_status": "/entry/instrument/beam_stop_2/status",
        "diode": "/entry/instrument/beam_stop_2/data",
        "sample_name": "/entry/sample/name",
        "sample_description": "/entry/sample/description",
        "samx": "/entry/sample/x_translation",
        "samy": "/entry/sample/y_translation",
        "temp": "/entry/sample/temperature_log"
    },

    "h5_dataset_calculated_input_values": {
        "/entry/instrument/source/distance": ('samz', lambda x: -33800. - x),
        "/entry/instrument/slit_0/distance": ('samz', lambda x: -33800. + 12100. - x),
        "/entry/instrument/slit_1/distance": ('samz', lambda x: -33800. + 26000. - x),
        "/entry/instrument/monochromator/wavelength": ('mokev', lambda x: 12.3984193 / x),
        "/entry/instrument/monochromator/distance": ('samz', lambda x: -33800. + 28580. - x),
        "/entry/instrument/mirror/distance": ('samz', lambda x: -33800. + 29430. - x),
        "/entry/instrument/slit_2/distance": ('samz', lambda x: -33800. + 30660. - x),
        "/entry/instrument/slit_3/distance": ('samz', lambda x: 0.0 - x),
        "/entry/instrument/filter_set/distance": ('samz', lambda x: 0.0 - x),
        "/entry/instrument/filter_set/attenuator_transmission": ('ftrans', lambda x: 10. ** x),
        "/entry/instrument/slit_4/distance": ('samz', lambda x: 0.0 - x)
    }
}
